version: '3'

services:

  database:
    image: postgres:latest
    volumes:
      - database_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server/src:/app/server/src
    command: /app/server/node_modules/.bin/nodemon src/index.js
      
  app:
    volumes:
      - ./app/src:/usr/app/src
      - ./app/public:/usr/app/public
      - ./app/node_modules:/app/node_modules
    command: npm run start
    build: ./app
    ports:
      - "3000:3000"
    links:
      - server