version: "3"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    entrypoint: sh entrypoint.sh
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app
