version: "2"

services:

  server:
    build:
      context: ./server
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: /app/node_modules/.bin/nodemon src/index.js
      
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    links:
      - server
    ports:
      - "3000:3000"
    command: npm start