version: 2

jobs:
  build:
    docker:
      - image: 1maa/docker-compose
    working_directory: ~/app

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build with docker-compose
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml build

      - run:
          name: Start with docker-compose
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml up
